# -*- coding: utf-8 -*-
# 生成 lib/app/i18n_dict.g.dart：
#   kZhHantPhraseMap：源码中每个简体字面量 -> OpenCC s2twp 繁体（整句、台湾用语品质）
#   kZhHantCharMap  ：出现过的汉字逐字 s2t 备援（处理插值组合字串）
# 用法：pip install opencc-python-reimplemented && python tools/i18n/gen_dict.py
import pathlib
import re
import sys

from opencc import OpenCC

cc_phrase = OpenCC('s2twp')
cc_char = OpenCC('s2t')

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / 'lib'
OUT = LIB / 'app' / 'i18n_dict.g.dart'

CJK = re.compile(r'[一-鿿]')
SKIP_FILES = {'i18n.dart', 'i18n_dict.g.dart'}
SKIP_SUFFIXES = ('.pb.dart', '.pbenum.dart', '.pbjson.dart', '.pbserver.dart', '.g.dart')
# 与服务器回传值比对的字面量：不进整句表（codemod 也不会给它们加 .i18n）
PROTECTED = {'连载中', '漫画不存在'}

LITERAL = re.compile(r'"((?:[^"\\\r\n]|\\.)*)"|\'((?:[^\'\\\r\n]|\\.)*)\'')

def unescape(s):
    return (s.replace(r'\n', '\n').replace(r'\t', '\t').replace(r'\"', '"')
             .replace(r"\'", "'").replace(r'\$', '$').replace('\\\\', '\\'))

def dart_escape(s):
    return (s.replace('\\', '\\\\').replace('"', r'\"').replace('$', r'\$')
             .replace('\n', r'\n').replace('\t', r'\t'))

def strip_comments(line, state):
    # state: {'block': bool}；返回可扫描代码部分
    out = []
    i, n = 0, len(line)
    quote = None
    while i < n:
        ch = line[i]
        if state['block']:
            j = line.find('*/', i)
            if j < 0:
                return ''.join(out), state
            state['block'] = False
            i = j + 2
            continue
        if quote:
            out.append(ch)
            if ch == '\\' and i + 1 < n:
                out.append(line[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in ('"', "'"):
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == '/' and i + 1 < n and line[i + 1] == '/':
            return ''.join(out), state
        if ch == '/' and i + 1 < n and line[i + 1] == '*':
            state['block'] = True
            i += 2
            continue
        out.append(ch)
        i += 1
    return ''.join(out), state

phrases = {}
chars = set()
triple_warned = []

for f in sorted(LIB.rglob('*.dart')):
    if f.name in SKIP_FILES or f.name.endswith(SKIP_SUFFIXES):
        continue
    text = f.read_text(encoding='utf-8')
    if re.search(r"'''|\"\"\"", text) and CJK.search(text):
        # 粗检：有三引号又有中文的档案，提醒人工确认
        for m in re.finditer(r"('''|\"\"\")((?:.|\n)*?)\1", text):
            if CJK.search(m.group(2)):
                triple_warned.append(str(f.relative_to(ROOT)))
                break
    state = {'block': False}
    for line in text.splitlines():
        code, state = strip_comments(line, state)
        for m in LITERAL.finditer(code):
            raw = m.group(1) if m.group(1) is not None else m.group(2)
            if not raw or not CJK.search(raw):
                continue
            for ch in raw:
                if CJK.match(ch):
                    chars.add(ch)
            if '$' in raw:
                continue  # 插值字串走逐字备援
            key = unescape(raw)
            if key in PROTECTED:
                continue
            val = cc_phrase.convert(key)
            if val != key:
                phrases[key] = val

char_map = {}
for ch in sorted(chars):
    t = cc_char.convert(ch)
    if t != ch and len(t) == 1:
        char_map[ch] = t

lines = []
lines.append('// GENERATED by tools/i18n/gen_dict.py - DO NOT EDIT BY HAND')
lines.append('// 重新生成：pip install opencc-python-reimplemented && python tools/i18n/gen_dict.py')
lines.append('')
lines.append('/// 整句简->繁（台湾用语）对照，key 为源码简体字面量')
lines.append('const Map<String, String> kZhHantPhraseMap = {')
for k in sorted(phrases):
    lines.append('  "%s": "%s",' % (dart_escape(k), dart_escape(phrases[k])))
lines.append('};')
lines.append('')
lines.append('/// 逐字备援表（处理插值组合出的字串）')
lines.append('const Map<String, String> kZhHantCharMap = {')
for k in sorted(char_map):
    lines.append('  "%s": "%s",' % (dart_escape(k), dart_escape(char_map[k])))
lines.append('};')
lines.append('')

OUT.write_text('\n'.join(lines), encoding='utf-8', newline='')
print('phrases:', len(phrases), ' chars:', len(char_map))
if triple_warned:
    print('WARNING triple-quoted Chinese in:', *sorted(set(triple_warned)), sep='\n  ')
