# -*- coding: utf-8 -*-
# 生成 lib/app/i18n_dict.g.dart：
#   kZhHantPhraseMap：源码中每个简体字面量 -> OpenCC s2twp 繁体（整句、台湾用语品质，UI 快路径）
#   kZhHantConvMap  ：OpenCC 全量 简->繁(台湾用语) 词表（字表+词组+台湾用语回推键），
#                     供任意文本（服务器内容、插值字串）做最长词优先转换
# 用法：pip install opencc-python-reimplemented && python tools/i18n/gen_dict.py
import os
import pathlib
import re
import sys

import opencc as opencc_pkg
from opencc import OpenCC

cc_phrase = OpenCC('s2twp')
cc_char = OpenCC('s2t')
cc_t2s = OpenCC('t2s')

DICT_DIR = pathlib.Path(os.path.dirname(opencc_pkg.__file__)) / 'dictionary'

def load_dict_keys(name):
    keys = []
    p = DICT_DIR / name
    for line in p.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or '\t' not in line:
            continue
        keys.append(line.split('\t', 1)[0])
    return keys

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / 'lib'
OUT = LIB / 'app' / 'i18n_dict.g.dart'

CJK = re.compile(r'[一-鿿]')
SKIP_FILES = {'i18n.dart', 'i18n_dict.g.dart'}
SKIP_SUFFIXES = ('.pb.dart', '.pbenum.dart', '.pbjson.dart', '.pbserver.dart', '.g.dart')
# 与服务器回传值比对的字面量：不进整句表（codemod 也不会给它们加 .i18n）
PROTECTED = {'连载中', '漫画不存在'}

LITERAL = re.compile(r'"((?:[^"\\\r\n]|\\.)*)"|\'((?:[^\'\\\r\n]|\\.)*)\'')

def unescape(s):
    return (s.replace(r'\n', '\n').replace(r'\t', '\t').replace(r'\"', '"')
             .replace(r"\'", "'").replace(r'\$', '$').replace('\\\\', '\\'))

def dart_escape(s):
    return (s.replace('\\', '\\\\').replace('"', r'\"').replace('$', r'\$')
             .replace('\n', r'\n').replace('\t', r'\t'))

def strip_comments(line, state):
    # state: {'block': bool}；返回可扫描代码部分
    out = []
    i, n = 0, len(line)
    quote = None
    while i < n:
        ch = line[i]
        if state['block']:
            j = line.find('*/', i)
            if j < 0:
                return ''.join(out), state
            state['block'] = False
            i = j + 2
            continue
        if quote:
            out.append(ch)
            if ch == '\\' and i + 1 < n:
                out.append(line[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in ('"', "'"):
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == '/' and i + 1 < n and line[i + 1] == '/':
            return ''.join(out), state
        if ch == '/' and i + 1 < n and line[i + 1] == '*':
            state['block'] = True
            i += 2
            continue
        out.append(ch)
        i += 1
    return ''.join(out), state

phrases = {}
chars = set()
triple_warned = []

for f in sorted(LIB.rglob('*.dart')):
    if f.name in SKIP_FILES or f.name.endswith(SKIP_SUFFIXES):
        continue
    text = f.read_text(encoding='utf-8')
    if re.search(r"'''|\"\"\"", text) and CJK.search(text):
        # 粗检：有三引号又有中文的档案，提醒人工确认
        for m in re.finditer(r"('''|\"\"\")((?:.|\n)*?)\1", text):
            if CJK.search(m.group(2)):
                triple_warned.append(str(f.relative_to(ROOT)))
                break
    state = {'block': False}
    for line in text.splitlines():
        code, state = strip_comments(line, state)
        for m in LITERAL.finditer(code):
            raw = m.group(1) if m.group(1) is not None else m.group(2)
            if not raw or not CJK.search(raw):
                continue
            for ch in raw:
                if CJK.match(ch):
                    chars.add(ch)
            if '$' in raw:
                continue  # 插值字串走逐字备援
            key = unescape(raw)
            if key in PROTECTED:
                continue
            val = cc_phrase.convert(key)
            if val != key:
                phrases[key] = val

# === 全量转换词表（服务器内容用）===
conv_keys = set()
conv_keys.update(load_dict_keys('STCharacters.txt'))
conv_keys.update(load_dict_keys('STPhrases.txt'))
# 台湾用语/异体字的键是繁体，回推成简体作为键（例：軟件->软件），值走 s2twp 得 軟體
for name in ('TWPhrases.txt', 'TWVariants.txt'):
    for k in load_dict_keys(name):
        s = cc_t2s.convert(k)
        conv_keys.add(s)

conv_map = {}
max_key_len = 1
for k in conv_keys:
    if not k:
        continue
    v = cc_phrase.convert(k)
    if v != k:
        conv_map[k] = v
        if len(k) > max_key_len:
            max_key_len = len(k)

lines = []
lines.append('// GENERATED by tools/i18n/gen_dict.py - DO NOT EDIT BY HAND')
lines.append('// 重新生成：pip install opencc-python-reimplemented && python tools/i18n/gen_dict.py')
lines.append('')
lines.append('/// 整句简->繁（台湾用语）对照，key 为源码简体字面量')
lines.append('const Map<String, String> kZhHantPhraseMap = {')
for k in sorted(phrases):
    lines.append('  "%s": "%s",' % (dart_escape(k), dart_escape(phrases[k])))
lines.append('};')
lines.append('')
lines.append('/// 全量 简->繁(台湾用语) 词表，最长词优先扫描用（含单字与词组）')
lines.append('const int kZhHantMaxKeyLen = %d;' % max_key_len)
lines.append('const Map<String, String> kZhHantConvMap = {')
buf = []
for k in sorted(conv_map):
    buf.append('"%s": "%s",' % (dart_escape(k), dart_escape(conv_map[k])))
    if len(buf) >= 8:
        lines.append('  ' + ' '.join(buf))
        buf = []
if buf:
    lines.append('  ' + ' '.join(buf))
lines.append('};')
lines.append('')

OUT.write_text('\n'.join(lines), encoding='utf-8', newline='')
print('phrases:', len(phrases), ' conv entries:', len(conv_map), ' max key len:', max_key_len)
if triple_warned:
    print('WARNING triple-quoted Chinese in:', *sorted(set(triple_warned)), sep='\n  ')
