display_name: ZAI-X
package_name: zai_x
maintainer:
  name: xiaoyaocz
  email: xiaoyaocz@52uwp.com
priority: optional
section: x11
installed_size: 24400
essential: false
icon: assets/images/logo.png

keywords:
  - 再漫画
  - ZAI-X

generic_name: ZAI-X

categories:
  - Media

startup_notify: true